version: '3.8'

services:
  # MongoDB for User and Comment Services
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # MySQL for Recipe Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: recipe_platform_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/user-service
    depends_on:
      - mongodb

  # Recipe Service
  recipe-service:
    build:
      context: ./recipe-service
      dockerfile: Dockerfile
    container_name: recipe-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/recipe_platform_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=abc123
    depends_on:
      - mysql

  # Comment Service
  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    container_name: comment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/comment-service
    depends_on:
      - mongodb

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8083:8080"
    depends_on:
      - user-service
      - recipe-service
      - comment-service

volumes:
  mongodb_data:
  mysql_data:
